Announcement for new system and cloudstack retirement
kthcloud/docs pull request #16
Opened 2024-04-30 06:51 UTC by harsha5500

Hej,

I have added a short writeup for the retirement of cloud stack. Please feel free to reduce or modify (or even delete) the proposed announcement. It is not too technical at this point as I am still figuring out rancher but please add anything you deem necessary. 

Thank you.

Harsha

2024-04-30 07:00 UTC, saffronjam reviewed
Cloud stack & cloudstack --> CloudStack 

Otherwise it looks good! 😄

2024-04-30 07:01 UTC, harsha5500 commented
Got it will change the spelling and test on Hugo

2024-04-30 07:02 UTC, pierrelefevre requested changes

2024-04-30 07:02 UTC, pierrelefevre commented on hugo/content/News/2024-04-29.md
> +Fortunately, Emil was testing a new method to create VMs within a kubernetes cluster. This allowed us to run the entire infrastructure as pure kuberentes system. It also has the added advantage of ru
Kubernetes*

2024-04-30 08:19 UTC, harsha5500 commented
Fixed the changes and pushed to the harsha branch.

2024-04-30 08:34 UTC, pierrelefevre requested changes

2024-04-30 08:34 UTC, pierrelefevre commented on hugo/content/News/2024-04-29.md
> +title: My Overwritten Name
Should be your actual title

2024-04-30 08:34 UTC, pierrelefevre commented on hugo/content/News/2024-04-29.md
> +weight: 2 # Order in the list
We don't use weight in the news tab since they are sorted by filename (ISO date)

2024-04-30 08:35 UTC, pierrelefevre commented
Sorry missed the top metadata stuff before but otherwise LGTM, you can just check how it looks in the other blog posts like https://raw.githubusercontent.com/kthcloud/docs/main/hugo/content/News/2024-03-22.md

2024-04-30 10:44 UTC, harsha5500 commented
Oops! Fixed the title and pushed again

2024-04-30 11:02 UTC, pierrelefevre approved these changes
LGTM +1

2024-05-02 13:10 UTC, pierrelefevre commented
Hmm I thought this would have been merged already!

2024-05-02 13:10 UTC, merged